
package example;

import utils.Downloader;

/**
 *
 * @author FGroupIndonesia.com
 */
public class DemoFrame extends javax.swing.JFrame {

    /**
     * Creates new form DownloadWithProgressBar
     */
    public DemoFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonDownload = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();
        textfieldSource = new javax.swing.JTextField();
        textfieldDirSave = new javax.swing.JTextField();
        radioNormal = new javax.swing.JRadioButton();
        radioURL = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonDownload.setText("Download");
        buttonDownload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDownloadActionPerformed(evt);
            }
        });
        getContentPane().add(buttonDownload, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 140, 110, 30));
        getContentPane().add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 240, 20));

        textfieldSource.setText("http://localhost/testing/download.php");
        getContentPane().add(textfieldSource, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 252, -1));

        textfieldDirSave.setText("D:\\storage\\video\\Islamic\\contoh");
        getContentPane().add(textfieldDirSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 116, 250, -1));

        buttonGroup1.add(radioNormal);
        radioNormal.setText("Normal File");
        getContentPane().add(radioNormal, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, -1, -1));

        buttonGroup1.add(radioURL);
        radioURL.setSelected(true);
        radioURL.setText("URL");
        getContentPane().add(radioURL, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Progress : ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 130, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Save Directory :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 130, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Source : ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 130, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonDownloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDownloadActionPerformed
        Downloader tool = new Downloader();
        tool.setProgressBar(jProgressBar1);
        tool.setTargetAbsoluteDirectory(textfieldDirSave.getText());
        if (radioNormal.isSelected()) {
            tool.setSourceAbsoluteFile(textfieldSource.getText());
        } else if(radioURL.isSelected()){
            tool.setSourceURL(textfieldSource.getText());
        }

        tool.setOpenDirAfterComplete(true);
        
        tool.start();

    }//GEN-LAST:event_buttonDownloadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DemoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DemoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DemoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DemoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DemoFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonDownload;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JRadioButton radioNormal;
    private javax.swing.JRadioButton radioURL;
    private javax.swing.JTextField textfieldDirSave;
    private javax.swing.JTextField textfieldSource;
    // End of variables declaration//GEN-END:variables
}
